import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "react-components/sections/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevOps Days Lima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header
          logoText="DevOps Days Lima"
          navItems={[
            { text: "Speakers", href: "/speakers", variant: "text" },
            { text: "Agenda", href: "/agenda", variant: "text" },
            { text: "Sponsors", href: "/sponsors", variant: "text" },
            { text: "Inscribirme", href: "/inscribirme", variant: "secondary" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
