import type { Metadata } from "next";
import "./globals.css";

import { Space_Grotesk } from "next/font/google";
import Header, { NavItem } from "react-components/sections/Header";
import { container } from "@/globals/container";
import { IContentData } from "@/services/IContentData";
import { ContainerIdentifiers } from "@/globals/identifiers";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await container.get<IContentData>(ContainerIdentifiers.IContentData).getPages();

  const navItems: NavItem[] = pages
    .filter(({fields})=>fields.includedInNavbar)
    .map((page) => ({
      text: String(page.fields.title),
      href: `/${page.fields.slug}`,
      variant: "text",
    }));

  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable}`}
      >
        <Header
          logoText="DevOps Days Lima"
          navItems={[
            ...navItems,
            { text: "Inscribirme", href: "/inscribirme", variant: "secondary" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
